const sampleListings = [
  {
    title: "Luxury Beachfront Villa with Infinity Pool",
    description: "Escape to paradise in this stunning beachfront villa featuring an infinity pool with breathtaking ocean views. Wake up to the sound of waves and enjoy direct beach access. The villa features 4 spacious bedrooms, a gourmet kitchen, and a private terrace perfect for sunset cocktails. Ideal for families or groups seeking luxury and relaxation.",
    image: {
      filename: "beachfront_villa",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800", filename: "main" },
      { url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800", filename: "bedroom" },
      { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800", filename: "pool" },
    ],
    price: 25000,
    location: "Goa",
    country: "India",
    propertyType: "Entire place",
    guests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    amenities: ["WiFi", "Kitchen", "Pool", "Air conditioning", "Free parking", "TV", "Beach access", "BBQ grill"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: true,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: true,
    },
    category: "Beach",
    geometry: {
      type: "Point",
      coordinates: [73.7319, 15.2993] // Goa coordinates [longitude, latitude]
    },
    instantBook: true,
  },
  {
    title: "Mountain View Treehouse Retreat",
    description: "Experience the magic of living among the treetops in this unique treehouse overlooking the Himalayan peaks. This eco-friendly retreat offers a cozy atmosphere with modern amenities. Perfect for couples seeking a romantic getaway or solo travelers looking for peace and inspiration. Includes a private deck for stargazing.",
    image: {
      filename: "treehouse",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800", filename: "main" },
      { url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800", filename: "interior" },
    ],
    price: 8500,
    location: "Manali",
    country: "India",
    propertyType: "Entire place",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Heating", "Breakfast", "Workspace", "Fireplace"],
    houseRules: {
      checkIn: "3:00 PM",
      checkOut: "10:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Treehouses",
    geometry: {
      type: "Point",
      coordinates: [77.1892, 32.2396] // Manali coordinates
    },
    instantBook: false,
  },
  {
    title: "Historic Haveli with Royal Heritage",
    description: "Step back in time and experience the grandeur of Rajasthani royalty in this 200-year-old restored haveli. Featuring intricate jharokhas, hand-painted murals, and antique furnishings, this property offers a unique cultural experience. Enjoy traditional hospitality, rooftop dining with fort views, and easy access to heritage sites.",
    image: {
      filename: "haveli",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800", filename: "main" },
      { url: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800", filename: "courtyard" },
    ],
    price: 12000,
    location: "Jaipur",
    country: "India",
    propertyType: "Private room",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "TV", "Workspace"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Iconic Cities",
    geometry: {
      type: "Point",
      coordinates: [75.7873, 26.9124] // Jaipur coordinates
    },
    instantBook: true,
  },
  {
    title: "Modern Penthouse with City Skyline Views",
    description: "Live the high life in this ultra-modern penthouse apartment in the heart of Mumbai. Floor-to-ceiling windows offer stunning views of the city skyline and Arabian Sea. Features include a gourmet kitchen, home theater, private gym, and rooftop garden. Walking distance to Bandra's best restaurants and nightlife.",
    image: {
      filename: "penthouse",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?w=800", filename: "main" },
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", filename: "living" },
    ],
    price: 35000,
    location: "Mumbai",
    country: "India",
    propertyType: "Entire place",
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3.5,
    amenities: ["WiFi", "Kitchen", "Gym", "Air conditioning", "Free parking", "TV", "Pool", "Workspace"],
    houseRules: {
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: true,
      petsAllowed: true,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Luxe",
    geometry: {
      type: "Point",
      coordinates: [72.8347, 19.0596] // Mumbai coordinates
    },
    instantBook: true,
  },
  {
    title: "Cozy Houseboat on Dal Lake",
    description: "Experience the timeless charm of Kashmir on this beautifully crafted traditional houseboat. Featuring hand-carved walnut woodwork, Persian carpets, and a private shikara for lake exploration. Wake up to stunning mountain reflections and enjoy authentic Kashmiri cuisine prepared by your dedicated host.",
    image: {
      filename: "houseboat",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800", filename: "main" },
    ],
    price: 6500,
    location: "Srinagar",
    country: "India",
    propertyType: "Entire place",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Heating", "Breakfast", "Kitchen"],
    houseRules: {
      checkIn: "1:00 PM",
      checkOut: "10:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Lakefront",
    geometry: {
      type: "Point",
      coordinates: [74.7973, 34.0837] // Srinagar coordinates
    },
    instantBook: false,
  },
  {
    title: "Hillside Coffee Estate Bungalow",
    description: "Nestled among lush coffee plantations in Coorg, this colonial-era bungalow offers a perfect retreat. Enjoy misty mornings on the veranda, plantation walks, and home-cooked Coorgi cuisine. The property features spacious rooms with period furniture and a garden filled with exotic birds and butterflies.",
    image: {
      filename: "coffee_estate",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?w=800", filename: "main" },
    ],
    price: 9500,
    location: "Coorg",
    country: "India",
    propertyType: "Entire place",
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Free parking", "Breakfast", "Fireplace", "BBQ grill"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: false,
      petsAllowed: true,
      smokingAllowed: false,
      eventsAllowed: true,
    },
    category: "Countryside",
    geometry: {
      type: "Point",
      coordinates: [75.9064, 12.3375] // Coorg coordinates
    },
    instantBook: true,
  },
  {
    title: "Desert Camp Under the Stars",
    description: "Experience the magic of the Thar Desert in this luxury glamping setup. Sleep in a beautifully decorated tent with traditional Rajasthani furnishings. Enjoy camel safaris, folk music around the bonfire, and spectacular sunset views over the sand dunes. An unforgettable adventure awaits.",
    image: {
      filename: "desert_camp",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800", filename: "main" },
    ],
    price: 7500,
    location: "Jaisalmer",
    country: "India",
    propertyType: "Private room",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Breakfast", "Air conditioning"],
    houseRules: {
      checkIn: "4:00 PM",
      checkOut: "9:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Camping",
    geometry: {
      type: "Point",
      coordinates: [70.9083, 26.9157] // Jaisalmer coordinates
    },
    instantBook: false,
  },
  {
    title: "Backwater Villa with Private Jetty",
    description: "Discover the serene beauty of Kerala's backwaters from this traditional Keralan villa. Features include a private jetty for houseboat pickups, an Ayurvedic spa room, and a traditional nalukettu architecture. Watch the sunset over coconut palms while enjoying fresh seafood and toddy.",
    image: {
      filename: "backwater_villa",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800", filename: "main" },
    ],
    price: 15000,
    location: "Alleppey",
    country: "India",
    propertyType: "Entire place",
    guests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 4,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "Free parking", "Pool", "Hot tub", "Breakfast"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: true,
    },
    category: "Lakefront",
    geometry: {
      type: "Point",
      coordinates: [76.3388, 9.4981] // Alleppey coordinates
    },
    instantBook: true,
  },
  {
    title: "Himalayan Stone Cottage",
    description: "Perched on a hillside with panoramic views of snow-capped peaks, this traditional stone cottage offers an authentic mountain experience. Heated by a wood-burning stove, it's perfect for those seeking solitude and natural beauty. Trek to nearby villages or simply relax with a book and hot chai.",
    image: {
      filename: "stone_cottage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800", filename: "main" },
    ],
    price: 4500,
    location: "Dharamshala",
    country: "India",
    propertyType: "Entire place",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Heating", "Fireplace", "Free parking"],
    houseRules: {
      checkIn: "3:00 PM",
      checkOut: "10:00 AM",
      selfCheckIn: true,
      petsAllowed: true,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Mountains",
    geometry: {
      type: "Point",
      coordinates: [76.3234, 32.2190] // Dharamshala coordinates
    },
    instantBook: true,
  },
  {
    title: "French Colonial Villa in Pondicherry",
    description: "Experience the unique Franco-Tamil culture in this beautifully restored French colonial villa in the heart of White Town. High ceilings, vintage tiles, and a charming courtyard garden create an atmosphere of old-world elegance. Walk to the beach, cafes, and boutiques of this enchanting seaside town.",
    image: {
      filename: "colonial_villa",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?w=800", filename: "main" },
    ],
    price: 11000,
    location: "Pondicherry",
    country: "India",
    propertyType: "Entire place",
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "Breakfast", "Workspace", "TV"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: true,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Iconic Cities",
    geometry: {
      type: "Point",
      coordinates: [79.8083, 11.9416] // Pondicherry coordinates
    },
    instantBook: true,
  },
  {
    title: "Tea Garden Bungalow in Darjeeling",
    description: "Wake up to misty mountain mornings in this heritage bungalow surrounded by tea gardens. Watch the sunrise over Kanchenjunga, enjoy freshly plucked Darjeeling tea, and explore the charming hill town. Colonial-era charm meets modern comfort in this perfect Himalayan retreat.",
    image: {
      filename: "tea_bungalow",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?w=800", filename: "main" },
    ],
    price: 8000,
    location: "Darjeeling",
    country: "India",
    propertyType: "Private room",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Heating", "Breakfast", "Free parking", "Fireplace"],
    houseRules: {
      checkIn: "1:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Countryside",
    geometry: {
      type: "Point",
      coordinates: [88.2627, 27.0360] // Darjeeling coordinates
    },
    instantBook: false,
  },
  {
    title: "Luxury Safari Lodge near Ranthambore",
    description: "Experience wildlife in style at this luxury safari lodge on the edge of Ranthambore National Park. Each cottage features a private deck overlooking the wilderness. Enjoy guided safaris to spot tigers, gourmet dining under the stars, and relaxing spa treatments after your adventures.",
    image: {
      filename: "safari_lodge",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800", filename: "main" },
    ],
    price: 22000,
    location: "Ranthambore",
    country: "India",
    propertyType: "Private room",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Pool", "Breakfast", "Hot tub"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Farms",
    geometry: {
      type: "Point",
      coordinates: [76.5026, 26.0173] // Ranthambore coordinates
    },
    instantBook: true,
  },
  {
    title: "Artistic Loft in Bangalore Tech Hub",
    description: "A creative space designed for digital nomads and tech enthusiasts. This industrial-chic loft in Koramangala features high-speed WiFi, a dedicated workspace, and smart home automation. Walking distance to top restaurants, cafes, and startups. Perfect for work-from-anywhere professionals.",
    image: {
      filename: "tech_loft",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800", filename: "main" },
    ],
    price: 5500,
    location: "Bangalore",
    country: "India",
    propertyType: "Entire place",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "TV", "Workspace", "Washer", "Gym"],
    houseRules: {
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: true,
      petsAllowed: true,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Trending",
    geometry: {
      type: "Point",
      coordinates: [77.5946, 12.9716] // Bangalore coordinates
    },
    instantBook: true,
  },
  {
    title: "Heritage Palace Suite in Udaipur",
    description: "Live like royalty in this palace suite overlooking the shimmering Lake Pichola. Ornate marble interiors, antique furnishings, and personalized butler service create an unforgettable experience. Watch the sunset paint the city golden from your private balcony while sipping on royal cocktails.",
    image: {
      filename: "palace_suite",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800", filename: "main" },
    ],
    price: 45000,
    location: "Udaipur",
    country: "India",
    propertyType: "Hotel room",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Pool", "Breakfast", "Hot tub", "Gym", "TV"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Castles",
    geometry: {
      type: "Point",
      coordinates: [73.6915, 24.5854] // Udaipur coordinates
    },
    instantBook: true,
  },
  {
    title: "Secluded Beach Hut in Andaman",
    description: "Disconnect from the world in this eco-friendly beach hut steps from pristine turquoise waters. Built with sustainable materials, it offers basic comforts amidst extraordinary natural beauty. Snorkel colorful reefs, kayak through mangroves, and fall asleep to the rhythm of gentle waves.",
    image: {
      filename: "beach_hut",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800", filename: "main" },
    ],
    price: 5000,
    location: "Havelock Island",
    country: "India",
    propertyType: "Entire place",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["Beach access", "Breakfast"],
    houseRules: {
      checkIn: "12:00 PM",
      checkOut: "10:00 AM",
      selfCheckIn: true,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Beach",
    geometry: {
      type: "Point",
      coordinates: [92.9879, 11.9847] // Havelock coordinates
    },
    instantBook: false,
  },
  {
    title: "Modern Apartment in New Delhi",
    description: "Stay in the heart of India's capital in this sleek, modern apartment. Ideally located near Connaught Place, it offers easy access to historical monuments, shopping, and nightlife. Features a fully equipped kitchen, smart TV, and dedicated workspace for business travelers.",
    image: {
      filename: "delhi_apt",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGFwYXJ0bWVudHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", filename: "main" },
    ],
    price: 6000,
    location: "New Delhi",
    country: "India",
    propertyType: "Entire place",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Air conditioning", "TV", "Washer", "Workspace", "Free parking"],
    houseRules: {
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: true,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Iconic Cities",
    geometry: {
      type: "Point",
      coordinates: [77.2090, 28.6139] // New Delhi coordinates
    },
    instantBook: true,
  },
  {
    title: "Riverside Cottage in Rishikesh",
    description: "Find your zen at this peaceful cottage on the banks of the holy Ganges. Perfect for yoga enthusiasts and spiritual seekers, it offers easy access to ashrams, meditation centers, and adventure sports. Wake up to mountain views and the soothing sound of the river.",
    image: {
      filename: "rishikesh_cottage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?w=800", filename: "main" },
    ],
    price: 3500,
    location: "Rishikesh",
    country: "India",
    propertyType: "Entire place",
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Free parking", "Breakfast"],
    houseRules: {
      checkIn: "1:00 PM",
      checkOut: "10:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Mountains",
    geometry: {
      type: "Point",
      coordinates: [78.2676, 30.0869] // Rishikesh coordinates
    },
    instantBook: true,
  },
  {
    title: "Spice Plantation Homestay in Munnar",
    description: "Experience life on a working spice plantation in the rolling hills of Munnar. Learn about cardamom, pepper, and tea cultivation. The homestay offers comfortable rooms, home-cooked Kerala cuisine, and guided plantation walks. A refreshing escape into nature's lap.",
    image: {
      filename: "munnar_homestay",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?w=800", filename: "main" },
    ],
    price: 4000,
    location: "Munnar",
    country: "India",
    propertyType: "Private room",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Breakfast", "Free parking", "Kitchen"],
    houseRules: {
      checkIn: "12:00 PM",
      checkOut: "10:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Farms",
    geometry: {
      type: "Point",
      coordinates: [77.0595, 10.0889] // Munnar coordinates
    },
    instantBook: false,
  },
  {
    title: "Luxury Villa with Private Pool in Alibaug",
    description: "Just a short ferry ride from Mumbai, this stunning villa offers a perfect weekend escape. Features include a private pool, landscaped gardens, outdoor BBQ area, and spacious interiors. Ideal for family gatherings, celebrations, or a relaxing retreat from city life.",
    image: {
      filename: "alibaug_villa",
      url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG9vbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800", filename: "main" },
    ],
    price: 28000,
    location: "Alibaug",
    country: "India",
    propertyType: "Entire place",
    guests: 12,
    bedrooms: 5,
    beds: 6,
    bathrooms: 5,
    amenities: ["WiFi", "Kitchen", "Pool", "Air conditioning", "Free parking", "TV", "BBQ grill", "Beach access"],
    houseRules: {
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: true,
      petsAllowed: true,
      smokingAllowed: false,
      eventsAllowed: true,
    },
    category: "Amazing Pools",
    geometry: {
      type: "Point",
      coordinates: [72.8719, 18.6414] // Alibaug coordinates
    },
    instantBook: true,
  },
  {
    title: "Boutique Stay in Varanasi Old City",
    description: "Immerse yourself in the spiritual heart of India at this boutique guesthouse overlooking the sacred Ganges. Watch the mesmerizing evening aarti from your window. The property combines traditional architecture with modern amenities and offers guided heritage walks through ancient lanes.",
    image: {
      filename: "varanasi_boutique",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    images: [
      { url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=800", filename: "main" },
    ],
    price: 5500,
    location: "Varanasi",
    country: "India",
    propertyType: "Private room",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Air conditioning", "Breakfast", "TV"],
    houseRules: {
      checkIn: "1:00 PM",
      checkOut: "11:00 AM",
      selfCheckIn: false,
      petsAllowed: false,
      smokingAllowed: false,
      eventsAllowed: false,
    },
    category: "Iconic Cities",
    geometry: {
      type: "Point",
      coordinates: [83.0007, 25.3176] // Varanasi coordinates
    },
    instantBook: true,
  },
];

module.exports = { data: sampleListings };